[project]
name = "sface-yunet-demo"
version = "0.1.1"
description = "Sface and Yunet demo"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.5",
    "opencv-python>=4.11.0.86",
    "tqdm>=4.67.1",
]
